package com.example.statpump.InterfaceAugmentation;

import java.util.ArrayList;
import java.util.List;

import com.example.statpump.R;

import android.content.Context;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.Spinner;
/**
 * Handles some user input in the interface
 * @author Jeff
 *
 */
public class ManageInput 
{
	static Context context;
	static Spinner sportSpinner;
	static Spinner sportSpecSpinner;
	static ImageView sportLogo;
	static String selectedSport;
	static String selectedSportSpec;
	
	/**
	 * Populates the sport spinner
	 * @param spinner
	 * @param cont
	 */
	public static void populateSpinner(Spinner spinner, Context cont)
	{
		sportSpinner = spinner;
		context = cont;
		List<String> sports = new ArrayList<String>();
		sports.add("Select a Sport");
		sports.add("Soccer");
		sports.add("American Football");
		sports.add("Australian Football");
		sports.add("Baseball");
		sports.add("Basketball");
		sports.add("Cricket");
		sports.add("Golf");
		sports.add("Handball");
		sports.add("Hockey");
		sports.add("Motorsports");
		sports.add("Rugby");
		sports.add("Tennis");
		sports.add("Volleyball");
		
		//Setting the adapter
		ArrayAdapter<String> spinnerArrayAdapter = new ArrayAdapter<String>(context, 
				android.R.layout.simple_spinner_dropdown_item, sports);
		sportSpinner.setAdapter(spinnerArrayAdapter);
	}
	
	/**
	 * Populates the second spinner with the subset of data
	 * (specific versions of the sports)
	 */
	public static void populateSpecSpinner(String selection, Spinner spinner, Context cont, ImageView image)
	{
		sportSpecSpinner = spinner;
		spinner.setAdapter(null);
		List<String> sports = new ArrayList<String>();
		sports.add("Specific Types of the Sport");
		if(selection.equals("Soccer"))
		{
			image.setImageResource(R.drawable.soccer);
		}
		else if(selection.equals("American Football"))
		{
			image.setImageResource(R.drawable.football);
			sports.add("AFL - Austria");
			sports.add("CFL - Canada");
			sports.add("CLAF - Czech Republic");
			sports.add("National Ligaen - Denmark");
			sports.add("EFL - Europe");
			sports.add("EFAF Cup - Europe");
			sports.add("Vaahteraliiga - Finland");
			sports.add("Championnat Elite - France");
			sports.add("GFL - Germany");
			sports.add("IFL - Italy");
			sports.add("Eerste Divisie - Netherlands");
			sports.add("1. Divisjon - Norway");
			sports.add("PLFA - Poland");
			sports.add("Superserien - Sweden");
			sports.add("NLA - Switzerland");
			sports.add("NFL - United States");
			sports.add("NCAA Division 1 FBS - United States");
			sports.add("AFL - United States");
			sports.add("IFAF World Cup - World");
		}
		else if(selection.equals("Australian Football"))
		{
			image.setImageResource(R.drawable.ausfootball);
			sports.add("AFL - Australia");
			sports.add("SANFL - Australia");
			sports.add("Foxtel Cup - Australia");
			sports.add("DAFL - Denmark");
			sports.add("AFLG - Germany");
			sports.add("SAFF Premier League - Sweden");
			sports.add("International Cup - World");
		}
		else if(selection.equals("Baseball"))
		{
			image.setImageResource(R.drawable.baseball);
			sports.add("Asian Series - Asia");
			sports.add("ABL - Australia");
			sports.add("ABL - Austria");
			sports.add("CPBL - Chinese Taipei");
			sports.add("LCPB - Colombia");
			sports.add("Extraliga - Czech Republic");
			sports.add("LIDOM - Dominican Republic");
			sports.add("European Championship - Europe");
			sports.add("European Championship Qualifiers - Europe");
			sports.add("European Cup - Europe");
			sports.add("Qualifier European Cup - Europe");
			sports.add("U21 European Championship - Europe");
			sports.add("Miesten SM-sarja - Finland");
			sports.add("Division 1 - France");
			sports.add("Baseball Bundesliga - Germany");
			sports.add("NBL - Great Britain");
			sports.add("IBL - Italy");
			sports.add("NPB - Japan");
			sports.add("KPB - Korea Republic");
			sports.add("LBL - Lithuania");
			sports.add("LMB - Mexico");
			sports.add("LMP - Mexico");
			sports.add("Hoofdklasse - Netherlands");
			sports.add("NBL - Norway");
			sports.add("PRBL - Puerto Rico");
			sports.add("Division de Honor - Spain");
			sports.add("Elitserien - Sweden");
			sports.add("Nationalliga A - Switzerland");
			sports.add("MLB - United States");
			sports.add("International League - United States");
			sports.add("Pacific Coast League - United States");
			sports.add("LVBP - Venezuela");
			sports.add("World Cup - World");
			sports.add("World Baseball Classic - World");
			sports.add("WBC Qualifiers - World");
			sports.add("Intercontinental Cup - World");
			sports.add("Caribbean Series - World");
			sports.add("Haarlem Baseball Week - World");
			sports.add("World Port Tournament - World");
		}
		else if(selection.equals("Basketball"))
		{
			image.setImageResource(R.drawable.basketball);
			sports.add("Liga Nacional de Basquet");
			sports.add("FIBA Asia Cup - Asia");
			sports.add("Asia Championships Cup - Asia");
			sports.add("ASEAN Basketball League - Asia");
			sports.add("NBL - Australia");
			sports.add("WNBL - Australia");
			sports.add("Bundesliga - Austria");
			sports.add("Supercup - Austria");
			sports.add("Frauen Bundesliga - Austria");
			sports.add("Ligue  Ethias - Belgium");
			sports.add("Beker van Belgie - Belgium");
			sports.add("Supercup - Belgium");
			sports.add("NBB - Brazil");
			sports.add("NBL - Bulgaria");
			sports.add("NBL Canada - Canada");
			sports.add("CBA - China PR");
			sports.add("A1 Liga - Croatia");
			sports.add("NBL - Czech Republic");
			sports.add("ZBL - Czech Republic");
			sports.add("Basketligaen - Denmark");
			sports.add("British Baskeball Legaue - England");
			sports.add("Euroleague - Europe");
			sports.add("Eurocup - Europe");
			sports.add("Eurochallenge - Europe");
			sports.add("Euroleague Women - Europe");
			sports.add("Eurocup Women - Europe");
			sports.add("Eurobasket - Europe");
			sports.add("Eurobasket Women - Europe");
			sports.add("Eurobasket Qualifiers - Europe");
			sports.add("Eurobasket Qualifiers Women - Europe");
			sports.add("Adriatic League - Europe");
			sports.add("VTB League - Europe");
			sports.add("Balkan League - Europe");
			sports.add("Baltic League - Europe");
			sports.add("BBL Challenge Cup - Europe");
			sports.add("BBL Cup - Europe");
			sports.add("Eurobasket U18 C - Europe");
			sports.add("Eurobasket U18 C Women - Europe");
			sports.add("Eurobasket U20 - Europe");
			sports.add("Eurobasket U20 B - Europe");
			sports.add("Eurobasket U18 - Europe");
			sports.add("Eurobasket U18 B - Europe");
			sports.add("Eurobasket U16 - Europe");
			sports.add("Eurobasket U16 B - Europe");
			sports.add("Eurobasket U16 C - Europe");
			sports.add("Eurobasket Small Countries - Europe");
			sports.add("Eurobasket U20 Women - Europe");
			sports.add("Eurobasket U20 B Women - Europe");
			sports.add("Eurobasket U18 Women - Europe");
			sports.add("Eurobasket U18 B Women - Europe");
			sports.add("Eurobasket U16 Women - Europe");
			sports.add("Eurobasket U16 B Women - Europe");
			sports.add("Eurobasket U16 C Women - Europe");
			sports.add("Eurobasket Small Countries Women - Europe");
			sports.add("Korisliiga - Finald");
			sports.add("LNB Pro A - France");
			sports.add("LNB Pro B - France");
			sports.add("Nationale 1 - France");
			sports.add("Leaders Cup - France");
			sports.add("Coupe de France - France");
			sports.add("Match des Champions - France");
			sports.add("LFB - France");
			sports.add("Basketball Bundesliga - Germany");
			sports.add("Pro A - Germany");
			sports.add("Pro B - Germany");
			sports.add("BBL Champions Cup - Germany");
			sports.add("1. Bundesliga - Germany");
			sports.add("BBL Cup - Germany");
			sports.add("2. Bundesliga - Germany");
			sports.add("A1 Ethniki - Greece");
			sports.add("Kypello Ellados - Greece");
			sports.add("NB I - Hungary");
			sports.add("Ligat Haal - Israel");
			sports.add("Lega A Basket - Italy");
			sports.add("LegaDue - Italy");
			sports.add("Coppa Italia - Italy");
			sports.add("Supercoppa - Italy");
			sports.add("Lega Basket Femminile - Italy");
			sports.add("Coppa Italia Women - Italy");
			sports.add("JBL - Japan");
			sports.add("KBL - Korea Republic");
			sports.add("LBL - Latvia");
			sports.add("Lietuvos Krepsinio Lyga - Lithuania");
			sports.add("Centrobasket - N/C America");
			sports.add("Centrobasket Women - N/C America");
			sports.add("Dutch Basketball League - Netherlands");
			sports.add("BLNO - Norway");
			sports.add("PBA Commissioner's Cup - Philippines");
			sports.add("PBA Philippine Cup - Philippines");
			sports.add("PBA Governors Cup - Philippines");
			sports.add("Ekstraliga - Poland");
			sports.add("Puchar Polski - Poland");
			sports.add("Superpuchar - Poland");
			sports.add("PLKK - Poland");
			sports.add("LPB - Portugal");
			sports.add("Trofeu Antonio Pratas - Portugal");
			sports.add("PBL - Russia");
			sports.add("Kosarkaska Liga - Serbia");
			sports.add("Liga Telemach - Slovenia");
			sports.add("1.SKL Zenske - Slovenia");
			sports.add("Campeonato Suamericano - South America");
			sports.add("Liga SudAmericana - South America");
			sports.add("Supercopa Women - Spain");
			sports.add("ACB - Spain");
			sports.add("Adecco Oro - Spain");
			sports.add("Supercopa - Spain");
			sports.add("Copa del Rey - Spain");
			sports.add("Liga Femenina - Spain");
			sports.add("Ligan - Sweden");
			sports.add("LNA - Switzerland");
			sports.add("Turkiye Basketbol Ligleri - Turkey");
			sports.add("Turkiye Kupasi - Turkey");
			sports.add("Cumhurbaskanligi Kupasi - Turkey");
			sports.add("Kadinlar Basketbol Ligi - Turkey");
			sports.add("Superleague - Ukraine");
			sports.add("NBA - United States");
			sports.add("WNBA - United States");
			sports.add("NCAA Division 1 - United States");
			sports.add("NBA D-League - United States");
			sports.add("Liga Uruguaya - Uruguay");
			sports.add("LPB - Venezuela");
			sports.add("World Championships - World");
			sports.add("World Championships Women - World");
			sports.add("FIBA U19 World Cup - World");
			sports.add("FIBA U19 World Cup Women - World");
			sports.add("FIBA U17 World Cup - World");
			sports.add("FIBA U17 World Cup Women - World");
			sports.add("Olympics - World");
			sports.add("Olympics Women - World");
			sports.add("Olympic Qualification - World");
			sports.add("Olympic Qualification Women - World");
			sports.add("FIBA Americas - World");
			sports.add("Liga Americas - World");
			sports.add("FIBA Americas U18 - World");
		}
		else if(selection.equals("Cricket"))
		{
			image.setImageResource(R.drawable.cricket);
			sports.add("Asia Cup - Asia");
			sports.add("ACC Trophy Elite - Asia");
			sports.add("Asian Test Championship - Asia");
			sports.add("KFC Twenty20 Big Bash - Australia");
			sports.add("Ryobi One-Day Cup - Australia");
			sports.add("Scheffield Shield - Australia");
			sports.add("NCL - Bangladesh");
			sports.add("NCL One-Day - Bangladesh");
			sports.add("BPL T20 - Bangladesh");
			sports.add("County Championship 1 - England");
			sports.add("County Championship 2 - England");
			sports.add("Yorkshire Bank 40 - England");
			sports.add("Friends Life t20 - England");
			sports.add("India Premier League - India");
			sports.add("Carribean Twenty20 - N/C America");
			sports.add("Ford Trophy - New Zealand");
			sports.add("HRV Cup - New Zealand");
			sports.add("Plunket Shield - New Zealand");
			sports.add("Sunfoil Series - South Africa");
			sports.add("Momentum 1-Day Cup - South Africa");
			sports.add("T20 Series - South Africa");
			sports.add("Premier League - Sri Lanka");
			sports.add("Champions League Twenty20 - World");
			sports.add("ICC World Cup - World");
			sports.add("ICC World Twenty20 - World");
			sports.add("ICC World Twenty20 Qualifiers - World");
			sports.add("ICC Test Championship - World");
			sports.add("ICC ODI Championship - World");
			sports.add("Twenty20 Internationals - World");
			sports.add("ICC Champions Trophy - World");
			sports.add("ICC Intercontinental Cup - World");
			sports.add("ICC WCL Championship - World");
			sports.add("ICC World Cricket League - World");
			sports.add("ICC U19 World Cup - World");
		}
		else if(selection.equals("Golf"))
		{
			image.setImageResource(R.drawable.golf);
			sports.add("PGA Tour");
			sports.add("European Tour");
			sports.add("LPGA Tour");
			sports.add("Asian Tour");
			sports.add("Japan Golf Tour");
			sports.add("Sunshine Tours");
			sports.add("Web.com Tour");
			sports.add("Champions Tour");
		}
		else if(selection.equals("Handball"))
		{
			image.setImageResource(R.drawable.handball);
			sports.add("HLA - Austria");
			sports.add("OHB Cup - Austria");
			sports.add("HLA Supercup - Austria");
			sports.add("WHA - Austria");
			sports.add("1ste Nationale Heren - Belgium");
			sports.add("Coupe de Belgique - Belgium");
			sports.add("1ste Nationale Dames - Belgium");
			sports.add("Coupe de Belgique Women - Belgium");
			sports.add("Premijer Liga - Bosnia-Herzegovina");
			sports.add("Premijer Liga Women - Bosnia-Herzegovina");
			sports.add("Nationalna Liga - Bulgaria");
			sports.add("Nationalna Liga Women - Bulgaria");
			sports.add("Premijer Liga - Croatia");
			sports.add("HRL Zene - Croatia");
			sports.add("Extraliga - Czech Republic");
			sports.add("WHIL - Czech Republic");
			sports.add("Jack&Jones Ligaen");
			sports.add("Guldbargeren Ligaen - Denmark");
			sports.add("EHF Euro - Europe");
			sports.add("EHF Euro Qualifiers -  Europe");
			sports.add("WC Qualifying - Europe");
			sports.add("EHF Champions League");
			sports.add("EHF Cup - Europe");
			sports.add("EHF Cup Winner Cup - Europe");
			sports.add("EHF Challenge Cup - Europe");
			sports.add("EHF Euro U20 - Europe");
			sports.add("EHF Euro U20 Qualifiers - Europe");
			sports.add("EHF Euro U18 - Europe");
			sports.add("EHF Euro U18 Qualifiers - Europe");
			sports.add("Challenge Trophy - Europe");
			sports.add("SEHA Liga - Europe");
			sports.add("EHF Euro Women - Europe");
			sports.add("EHF Euro Qualifiers Women - Europe");
			sports.add("WC Qualifying Women - Europe");
			sports.add("EHF Women Champions League - Europe");
			sports.add("EHF Cup Women - Europe");
			sports.add("EHF Cup Winner Cup Women - Europe");
			sports.add("EHF Challenge Cup Women - Europe");
			sports.add("WC U21 Qualification - Europe");
			sports.add("WC U20 Qualifying Women - Europe");
			sports.add("Challenge Trophy Women - Europe");
			sports.add("Miesten SM-Liiga - Finland");
			sports.add("LNH Division 1 - France");
			sports.add("Pro D2 - France");
			sports.add("Trophee des Champions - France");
			sports.add("Division de Feminin - France");
			sports.add("Coupe de France - France");
			sports.add("Coupe de la Ligue - France");
			sports.add("Bundesliga - Germany");
			sports.add("2.Bundesliga - Germany");
			sports.add("3.Liga - Germany");
			sports.add("DHB Pokal - Germany");
			sports.add("Super Cup - Germany");
			sports.add("Frauen Bundesliga - Germany");
			sports.add("2.Bundesliga Frauen - Germany");
			sports.add("DHB Pokal Frauen - Germany");
			sports.add("Super Cup Frauen - Germany");
			sports.add("U19 Bundesliga - Germany");
			sports.add("A1 - Greece");
			sports.add("NB I - Hungary");
			sports.add("NBI Noi - Hungary");
			sports.add("N1 Deild - Iceland");
			sports.add("N1 Deild Kvenna - Iceland");
			sports.add("Supercoppa - Italy");
			sports.add("Serie A - Italy");
			sports.add("LRL - Lithuania");
			sports.add("Sales Lentz Ligue - Luxembourg");
			sports.add("Ere Divisie - Netherlands");
			sports.add("Ere Divisie Women - Netherlands");
			sports.add("Postenligaen - Norway");
			sports.add("Postenligaen Kvinner - Norway");
			sports.add("Ekstraklasa - Poland");
			sports.add("Ekstraklasa Kobiet");
			sports.add("1a Divisao - Portugal");
			sports.add("Liga Nationala - Romania");
			sports.add("Liga Nationala Feminina - Romania");
			sports.add("Superleague - Russia");
			sports.add("Superleague Women - Russia");
			sports.add("Extraliga - Slovakia");
			sports.add("1.SRL - Slovenia");
			sports.add("Liga Asobal - Spain");
			sports.add("Copa del Rey - Spain");
			sports.add("Division De Honor - Spain");
			sports.add("Elit Serien - Sweden");
			sports.add("Allsvenskan - Sweden");
			sports.add("Elitserien Damer - Sweden");
			sports.add("Allsvenskan Damer - Sweden");
			sports.add("Nationalliga A - Switzerland");
			sports.add("Schweizer Cup - Switzerland");
			sports.add("Supercup - Switzerland");
			sports.add("Swiss Premier League - Switzerland");
			sports.add("Schweizer Cup Women - Switzerland");
			sports.add("Superlig - Turkey");
			sports.add("Superliga - Ukraine");
			sports.add("Olympics - World");
			sports.add("Olympics Women - World");
			sports.add("Olympics Qualification");
			sports.add("Olympics Qualification Women - World");
			sports.add("World Championship - World");
			sports.add("World Championship Women - World");
			sports.add("World Cup U19 Women - World");
			sports.add("World Cup U20 Women - World");
			sports.add("World Cup U21 - World");
			sports.add("Super Globe - World");
			sports.add("World Cup U19 - World");
		}
		else if(selection.equals("Hockey"))
		{
			image.setImageResource(R.drawable.hockey);
			sports.add("ALH - Asia");
			sports.add("AIHL - Australia");
			sports.add("EHL - Austria");
			sports.add("Nationalliga - Austria");
			sports.add("Extraliga - Belarus");
			sports.add("Elite League - Belgium");
			sports.add("Memorial Cup - Canada");
			sports.add("OHL - Canada");
			sports.add("WHL - Canada");
			sports.add("LHJMQ - Canada");
			sports.add("Extraliga - Czech Republic");
			sports.add("1. Liga - Czech Republic");
			sports.add("Superisligaen - Denmark");
			sports.add("Elite League - England");
			sports.add("Meistriliiga - Estonia");
			sports.add("Continental Cup - Europe");
			sports.add("Euro Ice Hockey Challenge - Europe");
			sports.add("European Trophy - Europe");
			sports.add("Euro Hockey Tour - Europe");
			sports.add("Inter-National-League - Europe");
			sports.add("SM-Liiga - Finland");
			sports.add("Mestis - Finland");
			sports.add("Lique Magnus - France");
			sports.add("DEL - Germany");
			sports.add("2. Bundesliga - Germany");
			sports.add("Interliga - Hungary");
			sports.add("Serie A1 - Italy");
			sports.add("LHL - Latvia");
			sports.add("Eredivisie - Netherlands");
			sports.add("Bekercompetitie - Netherlands");
			sports.add("GET-ligaen - Norway");
			sports.add("PLH - Poland");
			sports.add("Campionatul National - Romania");
			sports.add("KHL - Russia");
			sports.add("VHL - Russia");
			sports.add("MHL - Russia");
			sports.add("Extraliga - Slovakia");
			sports.add("Slohokej Liga - Slovenia");
			sports.add("Liga Nacional - Spain");
			sports.add("Elitserien - Sweden");
			sports.add("HockeyAllsvenskan - Sweden");
			sports.add("Division 1 - Sweden");
			sports.add("Nationalliga A - Switzerland");
			sports.add("Nationalliga B - Switzerland");
			sports.add("PHL - Ukraine");
			sports.add("NHL - United States");
			sports.add("AHL - United States");
			sports.add("ECHL - United States");
			sports.add("CHL - United States");
			sports.add("FHL - United States");
			sports.add("SPHL - United States");
			sports.add("Olympic Qualification - World");
			sports.add("Olympic Qualification Women - World");
			sports.add("Olympics - World");
			sports.add("Olympics Women - World");
			sports.add("World Championship - World");
			sports.add("World Championship Div I - World");
			sports.add("World Championship Div II - World");
			sports.add("World Championship Div III - World");
			sports.add("World Championship U20 - World");
			sports.add("World Championship U18 - World");
			sports.add("World Championship Women - World");
			sports.add("World Championship Div I Women - World");
			sports.add("World Championship Div II Women - World");
			sports.add("World Championship Div III Women - World");
		}
		else if(selection.equals("Motorsports"))
		{
			image.setImageResource(R.drawable.car);
			sports.add("FIA F1 World Championship");
			sports.add("Nascar Sprint Cup Series");
			sports.add("FIA World Rally Championship");
			sports.add("Indycar");
			sports.add("Superkart");
			sports.add("Deutsche Tourenwagen Masters");
			sports.add("Dakar Series");
			sports.add("Formula Renault 3.5 Series");
			sports.add("British Formula 3");
			sports.add("Eurocup Formula Renault 2.0");
			sports.add("Formula Renault 2.0 ALPS");
			sports.add("Eurocup Megane Trophy");
			sports.add("Eurocup Clio");
			sports.add("ADAC Formel Masters");
			sports.add("FIM MotoGP World Championship");
			sports.add("Middle Easy Rally Championship");
			sports.add("Moto 2");
			sports.add("Moto 3");
			sports.add("Superbike World Championships");
			sports.add("Moto X1");
			sports.add("Moto X2");
			sports.add("AMA Pro AM Superbike");
			sports.add("Formula 3 Euro Series");
			sports.add("AMA Supercross");
			sports.add("Enduro E1");
			sports.add("Enduro E2");
			sports.add("Enduro E3");
			sports.add("FIA European Rally Championship");
			sports.add("GP2 Series");
			sports.add("GP3 Series");
			sports.add("Red Bull Rookies Cup");
			sports.add("Nascar Truck Series");
			sports.add("V8 Supercars");
			sports.add("BMW Talent Cup");
		}
		else if(selection.equals("Rugby"))
		{
			image.setImageResource(R.drawable.rugby);
			sports.add("National Rugby League - Australia");
			sports.add("Ron Massey Cup - Australia");
			sports.add("State of Origin - Australia");
			sports.add("Division 1 - Belgium");
			sports.add("Canadian Rugby Championship - Canada");
			sports.add("Extraliga - Czech Republic");
			sports.add("Aviva Premiership - England");
			sports.add("Super League - England");
			sports.add("Championship - England");
			sports.add("Championship 1 - England");
			sports.add("Northern Rail Cup - England");
			sports.add("Premiership 7s - England");
			sports.add("Aviva A League - England");
			sports.add("NCL - England");
			sports.add("RaboDirect PRO12 - Europe");
			sports.add("European Rugby Cup - Europe");
			sports.add("Six Nations - Europe");
			sports.add("European Nations Cup - Europe");
			sports.add("U20 European Championship - Europe");
			sports.add("U19 European Championship - Europe");
			sports.add("U18 European Championship - Europe");
			sports.add("U18 European Championship Div A - Europe");
			sports.add("U18 European Championship Div B - Europe");
			sports.add("U18 European Championship Div C - Europe");
			sports.add("U18 European Championship Div D - Europe");
			sports.add("Regional Rugby Championship - Europe");
			sports.add("North Sea Cup - Europe");
			sports.add("British & Irish Cup - Europe");
			sports.add("Viking Tri-Nations - Europe");
			sports.add("Anglo Welsh Cup - Europe");
			sports.add("Challenge Cup - Europe");
			sports.add("7's Grand Prix Series - Europe");
			sports.add("7's Division A - Europe");
			sports.add("Top 14 - France");
			sports.add("Pro D2 - France");
			sports.add("Bundesliga - Germany");
			sports.add("Super 12 - Italy");
			sports.add("Ereklasse - Netherlands");
			sports.add("1e Klasse - Netherlands");
			sports.add("ITM Cup - New Zealand");
			sports.add("Pacific Nations Cup - Oceania");
			sports.add("Superliga - Romania");
			sports.add("RBS Premier League - Scotland");
			sports.add("RBS National League - Scotland");
			sports.add("Currie Cup - South Africa");
			sports.add("Vodacom Cup - South Africa");
			sports.add("South American Rugby Championship - South America");
			sports.add("Division de Honor - Spain");
			sports.add("Division de Honor B - Spain");
			sports.add("Allsvenskan - Sweden");
			sports.add("Premiership - Wales");
			sports.add("World Cup - World");
			sports.add("Four Nations - World");
			sports.add("Rugby League World Cup - World");
			sports.add("Super 15 - World");
			sports.add("The Rugby Championship - World");
			sports.add("IRB Junior World Championship - World");
			sports.add("IRB Junior World Rugby Trophy - World");
			sports.add("Churchill Cup - World");
			sports.add("Test Series - World");
			sports.add("World Club Challenge - World");
			sports.add("RWC Sevens - World");
			sports.add("IRB Sevens World Series - World");
			sports.add("RLWC Qualifiers - World");
			sports.add("Americas Rugby Championship - World");
		}
		else if(selection.equals("Tennis"))
		{
			image.setImageResource(R.drawable.tennis);
			sports.add("ATP World Tour (Grand Slam)");
			sports.add("ATP World Tour (Masters)");
			sports.add("ATP World Tour (ATP500)");
			sports.add("ATP World Tour (ATP250)");
			sports.add("WTA Tour (Premier)");
			sports.add("WTA Tour (International)");
			sports.add("ATP Challenge Tour");
			sports.add("Davis Cup");
			sports.add("Fed Cup");
			sports.add("Hopman Cup (Team Tournament)");
		}
		else if(selection.equals("Volleyball"))
		{
			image.setImageResource(R.drawable.volleyball);
			sports.add("Serie A1 - Argentina");
			sports.add("Liga Femenina - Argentina");
			sports.add("Asian Volleyball Championship - Asia");
			sports.add("Asian Volleyball Championship Women - Asia");
			sports.add("Asian Cup - Asia");
			sports.add("Asian Cup Women - Asia");
			sports.add("Arab Championship - Asia");
			sports.add("Damen Volley League - Austria");
			sports.add("Herren Volley League - Austria");
			sports.add("Ere Divisie Dames - Belgium");
			sports.add("Liga Heren - Belgium");
			sports.add("Superliga Masculina - Brazil");
			sports.add("Superliga Feminina - Brazil");
			sports.add("Superliga - Bulgaria");
			sports.add("A1 Liga - Croatia");
			sports.add("Extraliga - Czech Republic");
			sports.add("Extraliga Zeny - Czech Republic");
			sports.add("European Championship - Europe");
			sports.add("European Championship Women - Europe");
			sports.add("CEV Champions League - Europe");
			sports.add("CEV Cup - Europe");
			sports.add("CEV Challenge Cup - Europe");
			sports.add("CEV Champions League Women - Europe");
			sports.add("CEV Cup Women - Europe");
			sports.add("CEV Challenge Cup Women - Europe");
			sports.add("European Championship Qualifiers - Europe");
			sports.add("European Championship Qualifiers Women - Europe");
			sports.add("U21 European Championship - Europe");
			sports.add("U20 European Championship Women - Europe");
			sports.add("MEVZA League - Europe");
			sports.add("MEVZA League Women - Europe");
			sports.add("WC Qualifying - Europe");
			sports.add("Schenker League - Europe");
			sports.add("WC Qualifying Women - Europe");
			sports.add("Olympics Qualification - Europe");
			sports.add("Olympics Qualification Women - Europe");
			sports.add("Miesten Liiga - Finland");
			sports.add("Naisten Liiga - Finland");
			sports.add("Ligue A - France");
			sports.add("Ligue B - France");
			sports.add("Nationale 1 - France");
			sports.add("Coupe de France - France");
			sports.add("Trophee des Champions - France");
			sports.add("Ligue A Feminin - France");
			sports.add("Division Excellence - France");
			sports.add("Nationale 1F - France");
			sports.add("Coupe de France Women - France");
			sports.add("Bundesliga - Germany");
			sports.add("2. Bundesliga - Germany");
			sports.add("Bundesliga Women - Germany");
			sports.add("2. Bundesliga Women - Germany");
			sports.add("DVV Pokal - Germany");
			sports.add("DVV Pokal Women - Germany");
			sports.add("A1 Volley Men - Greece");
			sports.add("A1 Volley Women - Greece");
			sports.add("Serie A1 Maschile - Italy");
			sports.add("Serie A2 Maschile - Italy");
			sports.add("Coppa Italia A1 - Italy");
			sports.add("Coppa Italia A2 - Italy");
			sports.add("Supercoppa - Italy");
			sports.add("Serie A1 Femminile - Italy");
			sports.add("Serie A2 Femminile - Italy");
			sports.add("Coppa Italia A1 Women - Italy");
			sports.add("Coppa Italia A2 Women - Italy");
			sports.add("Supercoppa Women - Italy");
			sports.add("V-League - Korea Republic");
			sports.add("V-League Women - Korea Republic");
			sports.add("Copa Panamericana U23 Women - N/C America");
			sports.add("Copa Panamericana - N/C America");
			sports.add("Copa Panamericana Women - N/C America");
			sports.add("WC Qualifying - N/C America");
			sports.add("WC Qualifying Women - N/C America");
			sports.add("Olympics Qualification - N/C America");
			sports.add("Olympics Qualification Women - N/C America");
			sports.add("U21 Continental Championship - N/C America");
			sports.add("U20 Continental Championship Women - N/C America");
			sports.add("U19 Continental Championship - N/C America");
			sports.add("U18 Continental Championship Women - N/C America");
			sports.add("Copa Panamericana U23 - N/C America");
			sports.add("Campeonato Centroamericano U23 - N/C America");
			sports.add("Campeonato Centroamericano U23 Women - N/C America");
			sports.add("A League - Netherlands");
			sports.add("Supercup - Netherlands");
			sports.add("DELA League - Netherlands");
			sports.add("Supercup Women - Netherlands");
			sports.add("Eliteserien Menn - Norway");
			sports.add("Eliteserien Kvinner - Norway");
			sports.add("Plusliga - Poland");
			sports.add("Plusliga Kobiet - Poland");
			sports.add("A1 Masculinos - Portugal");
			sports.add("A1 Femininos - Portugal");
			sports.add("Divizia A1 - Romania");
			sports.add("Super League - Russia");
			sports.add("Super League Women - Russia");
			sports.add("Wiener Stadtische Liga - Serbia");
			sports.add("Wiener Stadtische Liga Women - Serbia");
			sports.add("DOL Moski - Slovenia");
			sports.add("DOL Zenske - Slovenia");
			sports.add("Superliga Femenina - Spain");
			sports.add("Superliga Masculina - Spain");
			sports.add("Elitserien Herrar - Sweden");
			sports.add("Elitserien Damer - Sweden");
			sports.add("Nationalliga A - Switzerland");
			sports.add("Nationalliga A Women - Switzerland");
			sports.add("Erkekler 1. Ligi - Turkey");
			sports.add("Bayanlar 1. Ligi - Turkey");
			sports.add("World League - World");
			sports.add("FIVB World Grand Prix - World");
			sports.add("Olympics - World");
			sports.add("Olympics Women - World");
			sports.add("World Cup - World");
			sports.add("World Cup Women - World");
			sports.add("World Championship - World");
			sports.add("World Championship Women - World");
			sports.add("World Championship U21 - World");
			sports.add("World Championship U20 Women - World");
			sports.add("World Championship U19 - World");
			sports.add("World Championship U18 Women - World");
			sports.add("Grand Champions Cup - World");
			sports.add("Grand Champions Cup Women - World");
			sports.add("Final Four Cup - World");
			sports.add("Olympics Qualification - World");
			sports.add("Olympics Qualification Women - World");
			sports.add("FIVB Club World Championship - World");
			sports.add("FIVB Club World Championship Women - World");
		}
		ArrayAdapter<String> spinnerArrayAdapter = new ArrayAdapter<String>(context, 
				android.R.layout.simple_spinner_dropdown_item, sports);
		sportSpecSpinner.setAdapter(spinnerArrayAdapter);
	}
}
